# SPDX-FileCopyrightText: © 2020 Alexandros Theodotou <alex at zrythm dot org>
# SPDX-License-Identifier: FSFAP
github: zrythm
open_collective: zrythm
liberapay: Zrythm
custom: "https://paypal.me/zrythm"
